.TH stralloc_copyb 3
.SH NAME
stralloc_copyb \- copy data into a stralloc
.SH SYNTAX
.B #include <stralloc.h>

extern int \fBstralloc_copyb\fP(stralloc* \fIsa\fR,const char* \fIbuf\fR,unsigned int \fIlen\fR);
.SH DESCRIPTION
stralloc_copyb makes sure that \fIsa\fR has enough space allocated to hold
\fIlen\fR bytes.  Then it copies the first \fIlen\fR bytes from
\fIbuf\fR into the stralloc.

The data that \fIsa\fR previously contained is overwritten and truncated.
