.TH scan_charsetnskip 3
.SH NAME
scan_charsetnskip \- skip characters from set
.SH SYNTAX
.B #include <scan.h>

long \fBscan_charsetnskip\fP(const char* \fIsrc\fR, const char* \fIcharset\fR, unsigned long* \fIlimit\fR);
.SH DESCRIPTION
scan_charsetnskip returns the length of the maximum prefix of \fIsrc\fR
that consists solely of characters that occur in \fIcharset\fR (up to
and not including the \\0).
.SH "SEE ALSO"
scan_noncharsetnskip(3)
